# Default initial positions for dual_fr3_robot's ros2_control fake system

initial_positions:
  left_fr3_finger_joint1: 0
  left_fr3_joint1: 0
  left_fr3_joint2: -0.78539815
  left_fr3_joint3: 0
  left_fr3_joint4: -2.35619445
  left_fr3_joint5: 0
  left_fr3_joint6: 1.5707963
  left_fr3_joint7: 0
  right_fr3_finger_joint1: 0
  right_fr3_joint1: 0
  right_fr3_joint2: -0.78539815
  right_fr3_joint3: 0
  right_fr3_joint4: -2.35619445
  right_fr3_joint5: 0
  right_fr3_joint6: 1.5707963
  right_fr3_joint7: 0